name: timetable_example
description: A simple example app for the timetable package
version: 0.2.9
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  timetable:
    path: ../
  time_machine:
    git:
      url: https://github.com/alexandrsitnikov/time_machine
      ref: dd8190e9f98e2f1093509839dd966f5992775ded

flutter:
  uses-material-design: true

  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
